services:
  web:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: custom_apache_php
    platform: linux/x86_64
    ports:
      - "8080:80"
      - "8443:443"
    volumes:
      - ./html:/var/www/html
    environment:
      - APACHE_RUN_USER=www-data
      - APACHE_RUN_GROUP=www-data
    depends_on:
      - db

  db:
    image: mysql:8.0
    platform: linux/x86_64
    container_name: custom_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: custom_db
      MYSQL_USER: custom_user
      MYSQL_PASSWORD: custom_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: